# Generated by Django 4.2.3 on 2023-09-26 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customadmin", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialMedia",
        ),
    ]
