# Generated by Django 4.2.3 on 2023-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customadmin", "0002_delete_socialmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_admin", models.CharField(max_length=200)),
                ("instagram_admin", models.CharField(max_length=200)),
                ("twitter_admin", models.CharField(max_length=200)),
            ],
        ),
    ]
