# Generated by Django 4.2.3 on 2023-10-03 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="airport_booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "booking_type",
                    models.CharField(default="Airport Booking", max_length=100),
                ),
                (
                    "booking_id",
                    models.CharField(default="", max_length=100, unique=True),
                ),
                ("pickup_city", models.CharField(default="", max_length=100)),
                ("drop_city", models.CharField(default="", max_length=100)),
                ("mobile_b", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=50)),
                ("amount", models.CharField(default="", max_length=100)),
                ("date", models.CharField(default="", max_length=100)),
                ("time", models.CharField(default="", max_length=100)),
                ("remark", models.TextField(default="")),
                (
                    "flight_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gst_company",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gst_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "alternative_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "total",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "paid_amount",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "remaining_amount",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
            ],
        ),
    ]
