# Generated by Django 4.2.3 on 2023-10-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_perkmprices_ar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport_price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price1", models.CharField(max_length=100)),
                ("price2", models.CharField(max_length=100)),
                ("price3", models.CharField(max_length=100)),
                ("price4", models.CharField(max_length=100)),
                ("price5", models.CharField(max_length=100)),
                ("price6", models.CharField(max_length=100)),
                ("price7", models.CharField(max_length=100)),
                ("price8", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="PerKmPrices_AR",
        ),
    ]
