# Generated by Django 4.2.3 on 2023-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_airport_drop"),
    ]

    operations = [
        migrations.DeleteModel(
            name="airport_drop",
        ),
        migrations.AddField(
            model_name="airport_booking",
            name="selected_option",
            field=models.CharField(default="", max_length=100),
        ),
    ]
