# Generated by Django 4.2.3 on 2023-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0004_airport_price_delete_perkmprices_ar"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport_booking",
            name="distance",
            field=models.CharField(default="", max_length=200),
        ),
    ]
