# Generated by Django 4.2.3 on 2023-08-24 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0004_delete_airport_drop_airport_booking_selected_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airport_booking",
            name="drop_address",
        ),
        migrations.RemoveField(
            model_name="airport_booking",
            name="pickup_address",
        ),
    ]
