# Generated by Django 4.2.3 on 2023-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0005_airport_booking_distance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base_Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base1", models.CharField(max_length=100)),
                ("base2", models.CharField(max_length=100)),
                ("base3", models.CharField(max_length=100)),
                ("base4", models.CharField(max_length=100)),
            ],
        ),
    ]
