# Generated by Django 4.2.3 on 2023-09-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0006_airport_booking_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport_booking",
            name="alternative_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
