# Generated by Django 4.2.3 on 2023-09-04 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expiration_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
