# Generated by Django 4.2.3 on 2023-10-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0003_coupon_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
