# Generated by Django 4.2.3 on 2023-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0004_coupon_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="description",
            field=models.CharField(default="", max_length=200),
        ),
    ]
