# Generated by Django 4.2.3 on 2023-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="roundway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(default="", max_length=100, unique=True),
                ),
                ("pickup_city", models.CharField(default="", max_length=100)),
                ("drop_city", models.CharField(default="", max_length=100)),
                ("pickup_address", models.CharField(max_length=200)),
                ("drop_address", models.CharField(max_length=200)),
                ("mobile_b", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=50)),
                ("amount", models.CharField(default="", max_length=100)),
                ("date", models.CharField(default="", max_length=100)),
                ("re_date", models.CharField(default="", max_length=100)),
                ("time", models.CharField(default="", max_length=100)),
                ("remark", models.TextField(default="")),
                (
                    "gst_company",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gst_number", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
