# Generated by Django 4.2.3 on 2023-08-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roundway", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundway",
            name="return_date",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
