# Generated by Django 4.2.3 on 2023-08-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roundway", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundway",
            name="re_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
