# Generated by Django 4.2.3 on 2023-08-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roundway", "0002_alter_roundway_return_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roundway",
            name="return_date",
        ),
        migrations.AddField(
            model_name="roundway",
            name="days",
            field=models.CharField(default="", max_length=100),
        ),
    ]
