# Generated by Django 4.2.3 on 2023-08-24 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roundway", "0002_alter_roundway_re_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roundway",
            old_name="re_date",
            new_name="return_date",
        ),
    ]
