# Generated by Django 4.2.3 on 2023-08-25 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roundway", "0003_rename_re_date_roundway_return_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="roundway",
            new_name="roundway_booking",
        ),
    ]
