# Generated by Django 4.2.3 on 2023-10-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roundway", "0008_perkmprices_r"),
    ]

    operations = [
        migrations.AddField(
            model_name="roundway_booking",
            name="booking_type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
