# Generated by Django 4.2.3 on 2023-09-11 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="city",
        ),
    ]
