# Generated by Django 4.2.3 on 2023-09-11 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_remove_route_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="city",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="routes.city",
            ),
        ),
    ]
