# Generated by Django 4.2.3 on 2023-09-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0003_route_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="routes.city"
            ),
        ),
    ]
