# Generated by Django 4.2.3 on 2023-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0004_alter_route_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local_City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=100)),
                ("local_city", models.CharField(max_length=200)),
                ("custom_url", models.SlugField(unique=True)),
            ],
        ),
    ]
