# Generated by Django 4.2.3 on 2023-09-13 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0006_rename_city_city1_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dynamic_Local_City",
            new_name="Local_City",
        ),
    ]
