# Generated by Django 4.2.3 on 2023-09-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0007_rename_dynamic_local_city_local_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oneway_routes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("custom_url", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Roundway_routes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("custom_url", models.SlugField(unique=True)),
            ],
        ),
    ]
