# Generated by Django 4.2.3 on 2023-09-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0008_oneway_routes_roundway_routes"),
    ]

    operations = [
        migrations.AddField(
            model_name="roundway_routes",
            name="roundway_city",
            field=models.CharField(default="", max_length=100),
        ),
    ]
