# Generated by Django 4.2.3 on 2023-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oneway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="alternative_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
