# Generated by Django 4.2.3 on 2023-10-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oneway", "0002_perkmprices"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
