# Generated by Django 4.2.3 on 2023-10-03 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oneway", "0004_alter_booking_booking_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_type",
        ),
    ]
