# Generated by Django 4.2.3 on 2023-10-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oneway", "0005_remove_booking_booking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(default="", max_length=200),
        ),
    ]
