# Generated by Django 4.2.3 on 2023-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oneway", "0007_alter_onewayroute_premium_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="distance",
            field=models.CharField(default="", max_length=200),
        ),
    ]
