# Generated by Django 4.2.3 on 2023-10-06 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("oneway", "0009_onewayprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="onewayroute",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
