# Generated by Django 4.2.3 on 2023-10-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oneway", "0010_onewayroute_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="car_type",
            field=models.CharField(default="", max_length=200),
        ),
    ]
