# Generated by Django 4.2.3 on 2023-10-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oneway", "0011_booking_car_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="car_type",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
