# Generated by Django 4.2.3 on 2023-10-13 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oneway", "0012_alter_booking_car_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="car_type",
            new_name="car_name",
        ),
    ]
