# Generated by Django 4.2.3 on 2023-08-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0003_place_pp_cc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cc",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="local.pp"
            ),
        ),
        migrations.AlterField(
            model_name="pp",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="local.place"
            ),
        ),
    ]
