# Generated by Django 4.2.3 on 2023-08-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0005_remove_book_author_remove_cc_package_remove_pp_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="car",
        ),
        migrations.RemoveField(
            model_name="city",
            name="package",
        ),
        migrations.RemoveField(
            model_name="city",
            name="price",
        ),
        migrations.CreateModel(
            name="CarPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="local.car"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="local.city",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="local.package"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="packages",
            field=models.ManyToManyField(
                through="local.CarPackage", to="local.package"
            ),
        ),
    ]
