# Generated by Django 4.2.3 on 2023-08-16 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0008_alter_carpackage_car_alter_carpackage_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpackage",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="local.city"
            ),
        ),
    ]
