# Generated by Django 4.2.3 on 2023-08-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0009_alter_carpackage_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="local_booking",
            old_name="amount",
            new_name="car_price",
        ),
        migrations.RenameField(
            model_name="local_booking",
            old_name="mobile_b",
            new_name="mobile",
        ),
        migrations.RenameField(
            model_name="local_booking",
            old_name="drop_address",
            new_name="pick_up",
        ),
        migrations.RenameField(
            model_name="local_booking",
            old_name="local_city",
            new_name="selected_city",
        ),
        migrations.RemoveField(
            model_name="local_booking",
            name="pickup_address",
        ),
        migrations.AddField(
            model_name="local_booking",
            name="remark",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="local_booking",
            name="selected_package",
            field=models.CharField(default="", max_length=100),
        ),
    ]
