# Generated by Django 4.2.3 on 2023-08-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0010_rename_amount_local_booking_car_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="local_booking",
            name="gst_company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="local_booking",
            name="gst_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="local_booking",
            name="remark",
            field=models.TextField(),
        ),
    ]
