# Generated by Django 4.2.3 on 2023-08-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0011_local_booking_gst_company_local_booking_gst_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="local_booking",
            name="amount",
            field=models.CharField(default="", max_length=100),
        ),
    ]
