# Generated by Django 4.2.3 on 2023-08-25 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0013_local_booking_created_at_local_booking_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="local_booking",
            old_name="mobile",
            new_name="mobile_b",
        ),
    ]
