# Generated by Django 4.2.3 on 2023-08-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0014_rename_mobile_local_booking_mobile_b"),
    ]

    operations = [
        migrations.AddField(
            model_name="local_booking",
            name="booking_type",
            field=models.CharField(default="Local", max_length=100),
        ),
    ]
