# Generated by Django 4.2.3 on 2023-09-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0015_local_booking_booking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="local_booking",
            name="alternative_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
