# Generated by Django 4.2.3 on 2023-09-13 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0016_local_booking_alternative_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="City",
            new_name="Local_City",
        ),
    ]
