# Generated by Django 4.2.3 on 2023-09-13 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0017_rename_city_local_city"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Local_City",
            new_name="Local_City1",
        ),
    ]
