# Generated by Django 4.2.3 on 2023-10-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0020_local_booking_paid_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local_booking",
            name="booking_type",
            field=models.CharField(max_length=100),
        ),
    ]
