# Generated by Django 4.2.3 on 2023-10-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0023_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="button",
            field=models.CharField(default="", max_length=100),
        ),
    ]
