# Generated by Django 4.2.3 on 2023-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0024_car_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="container_image",
            field=models.ImageField(default="", upload_to="local_images/"),
        ),
    ]
