# Generated by Django 4.2.3 on 2023-10-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0025_car_container_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
