# Generated by Django 4.2.3 on 2023-10-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0027_car_bag_capacity_car_person_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="local_booking",
            name="car_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
