# Generated by Django 4.2.3 on 2023-10-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0028_local_booking_car_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="local_booking",
            name="gst",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="local_booking",
            name="car_name",
            field=models.CharField(max_length=100),
        ),
    ]
