# Generated by Django 4.2.3 on 2023-10-17 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("local", "0030_local_booking_base_fare"),
    ]

    operations = [
        migrations.RenameField(
            model_name="local_booking",
            old_name="base_fare",
            new_name="estimated_amount",
        ),
        migrations.RenameField(
            model_name="local_booking",
            old_name="gst",
            new_name="gst_amount",
        ),
    ]
